name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test -v -race ./...
